#
# cargo audit config file
#

# Advisories ignored because there are not yet any solution available.
[advisories]
ignore = [
    "RUSTSEC-2023-0071" # https://rustsec.org/advisories/RUSTSEC-2023-0071
]