name: agent-unit-tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: pshampanier/squill-ci
      options: --security-opt seccomp=unconfined
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Checkout loose-sqlparser-rs repository
        uses: actions/checkout@v4
        with:
          repository: squill-app/loose-sqlparser-rs
          path: loose-sqlparser-rs

      - name: Checkout squill-drivers repository
        uses: actions/checkout@v4
        with:
          repository: squill-app/squill-drivers
          path: squill-drivers

        # The test suite cannot be run as root because some of the tests such as utils::users::tests::test_create_user
        # and utils::users::tests::test_delete_user would fail.
      - name: Generate code coverage
        working-directory: ./
        env:
          CI_POSTGRES_CONNECTION_STRING: ${{ secrets.CI_POSTGRES_CONNECTION_STRING }}
          VITE_AGENT_ADDRESS: 127.0.0.1
          VITE_AGENT_PORT: 8080
          VITE_AGENT_API_KEY: x-dev-api-key
        run: |
          chmod -R a+rw .
          su ci --command="cargo tarpaulin --target-dir=build --timeout 120 --out xml"

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          directory: ./build
          verbose: false

      - name: Security audit
        if: always()
        working-directory: ./
        run: |
          cargo audit
